//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTurnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioTurno
    {
        public int IdCambioTurno { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdUsuarioold { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string VObservaciones { get; set; }
        public Nullable<int> IdTurnoUsuario { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual TurnoUsuario TurnoUsuario { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
