//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTurnos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contrato
    {
        public int IdContrato { get; set; }
        [Display(Name = "Fecha de Inicio")]
        public Nullable<System.DateTime> DFechaInicio { get; set; }
        [Display(Name = "Fecha Termino")]
        public Nullable<System.DateTime> DFechaFin { get; set; }
        
        public Nullable<int> IdTipoContrato { get; set; }
      
        public Nullable<int> IdUsuario { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
