//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTurnos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Permisos
    {
        [Display(Name = "Id Permiso")]
        public int IdPermisos { get; set; }
        [Display(Name = "Fecha Inicio")]
        public Nullable<System.DateTime> DFechaInicio { get; set; }
        [Display(Name = "Cantidad de Días")]
        public Nullable<int> ICantDias { get; set; }
        [Display(Name = "Cantidad de Horas")]
        public Nullable<int> ICantHoras { get; set; }
        [Display(Name = "Fecha Término")]
        public Nullable<System.DateTime> DFechaFin { get; set; }
        public Nullable<int> IdTipoPermiso { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual TipoPermiso TipoPermiso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
