//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTurnos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurnosAduanaEntities : DbContext
    {
        public TurnosAduanaEntities()
            : base("name=TurnosAduanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalidadJuridica> CalidadJuridica { get; set; }
        public virtual DbSet<CambioTurno> CambioTurno { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Lugar> Lugar { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoContrato> TipoContrato { get; set; }
        public virtual DbSet<TipoPermiso> TipoPermiso { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<TurnoUsuario> TurnoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
