//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTurnos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TurnoUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TurnoUsuario()
        {
            this.CambioTurno = new HashSet<CambioTurno>();
        }

        [Display(Name = "Id Turno Usuario")]
        public int IdTurnoUsuario { get; set; }
        [Display(Name = "Fecha Inicio")]
        public Nullable<System.DateTime> DFechaincio { get; set; }
        [Display(Name = "Fecha Término")]
        public Nullable<System.DateTime> DFechaTermino { get; set; }
        public Nullable<int> IdLugar { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambioTurno> CambioTurno { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Turnos Turnos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
